# 1. Save to a local file in your project folder instead of RAM!
spring.datasource.url=jdbc:h2:file:./vault_database

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. Update tables instead of dropping them!
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
server.port=8080
spring.application.name=password-vault